### PR TITLE
fix for spectrum view, change to production js build

### PR DESCRIPTION
**Pull request by colin-combe**
@sureshhewabi - fix for spectrum view

How are we arranging deploying? Can i deploy by just merging into pride branch?

### CODE REVIEW

**Comment by sureshhewabi** [comment]
yes merging branch will automatically deploy

**Comment by colin-combe** [comment]
i'll merge...

**Comment by colin-combe** [comment]
it worked!

**Comment by sureshhewabi** [comment]
Great! Thanks

**Pull request merged**
